GDRIVE_CREDENTIALS_JSON = """
{
"installed":{
"client_id":"482868414801-m4khli2fu7c75loiek9dh91pvq88gnmk.apps.googleusercontent.com","project_id":"itech-crl-images","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost"]
}
}
"""

GDRIVE_IMAGE_FOLDER_ID = "1Cn6_zg9G1ahpSRT3-N8tt3XPATcoxg5C"
